# Liebherr / Prionoth Data Demo

In dieser Demo habe ich mich mit dem Laden von JSON-Event-Logs beschäftigt. Dieses Verfahren ist die basis für das gemeinsame Projekt mit Liebherr/Prinoth. Wir planen eine Analyse von einschlägigen Maschinen-Logs zur Untersuchung von Mustern innerhalb dieser Daten. Die Daten werden von Pistengerägen (Prinoth) und diversen Maschinen (Liebherr) bereitgestellt. Inhalt des Projekts ist zum einen das Finden einer passenden Datenstruktur die für beide Unternehmen passen kann und andererseits einer Lade/Verarbeitungs/Analysetechnik.

In [1]:
from pandas import read_json

## Load Data

In [2]:
data = read_json(
    "../data/liebherr_prinoth_demo.json",
    convert_dates=["ts_utc"],
    dtype={
        'machine_id': 'object',
        'ts_utc': "datetime",
        'event_id': "object",
        "group": "object",
        "code": "object",
        "severity": "object",
        "priority": "int64",
        "text": "str",
        "value": "float64",
        "unit": "object",
        "source": "object"
    }
)

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   machine_id  12 non-null     object
 1   ts_utc      12 non-null     str
 2   event_id    12 non-null     object
 3   group       12 non-null     object
 4   code        12 non-null     object
 5   severity    12 non-null     object
 6   priority    12 non-null     int64
 7   text        12 non-null     str
 8   value       6 non-null      float64
 9   unit        6 non-null      object
 10  source      12 non-null     object
dtypes: float64(1), int64(1), object(7), str(2)
memory usage: 1.2+ KB

In [20]:
data.to_csv("../data/liebherr_prinoth_demo.csv", index=False)

In [21]:
data.head()

,machine_id,ts_utc,event_id,group,code,severity,priority,text,value,unit,source
0,LH-A-042,2026-05-14T07:15:02Z,e0001,Powertrain,PT_1001,info,4,Ignition ON,NaN,NaN,ECU
1,LH-A-042,2026-05-14T07:15:06Z,e0002,Powertrain,PT_1100,info,4,Engine start requested,NaN,NaN,ECU
2,LH-A-042,2026-05-14T07:15:08Z,e0003,Powertrain,PT_1101,info,4,Engine running,NaN,NaN,ECU
3,LH-A-042,2026-05-14T07:17:19Z,e0004,Hydraulic,HY_2003,warning,3,Hydraulic oil temperature high,92.4,C,ECU
4,LH-A-042,2026-05-14T07:17:45Z,e0005,Hydraulic,HY_2004,warning,3,Hydraulic pressure oscillation detected,18.2,bar_pp,ECU

In [22]:
from pandas import read_csv

class EventLoader:

    def __init__(self, use_columns=False, ts_column=0, dim_columns=False, fact_columns=False, file_path = None):

        self.use_columns = use_columns
        self.ts_column = ts_column
        self.dim_columns = dim_columns
        self.fact_columns = fact_columns
        self.file_path = file_path

        self.data = None

    def read_csv(self):
        data = read_csv(self.file_path)
        return data

In [23]:
d = EventLoader(file_path="../data/liebherr_prinoth_demo.csv")

In [24]:
d.read_csv()

,machine_id,ts_utc,event_id,group,code,severity,priority,text,value,unit,source
0,LH-A-042,2026-05-14T07:15:02Z,e0001,Powertrain,PT_1001,info,4,Ignition ON,NaN,NaN,ECU
1,LH-A-042,2026-05-14T07:15:06Z,e0002,Powertrain,PT_1100,info,4,Engine start requested,NaN,NaN,ECU
2,LH-A-042,2026-05-14T07:15:08Z,e0003,Powertrain,PT_1101,info,4,Engine running,NaN,NaN,ECU
3,LH-A-042,2026-05-14T07:17:19Z,e0004,Hydraulic,HY_2003,warning,3,Hydraulic oil temperature high,92.40,C,ECU
4,LH-A-042,2026-05-14T07:17:45Z,e0005,Hydraulic,HY_2004,warning,3,Hydraulic pressure oscillation detected,18.20,bar_pp,ECU
5,LH-A-042,2026-05-14T07:18:03Z,e0006,Sensor,SN_3102,error,2,Temperature sensor implausible,NaN,NaN,ECU
6,LH-A-042,2026-05-14T07:18:05Z,e0007,Hydraulic,HY_2100,error,2,Hydraulic derate active,0.70,limit_factor,ECU
7,LH-A-042,2026-05-14T07:18:18Z,e0008,Connectivity,CN_4001,warning,3,Telematics buffer nearing capacity,0.88,ratio,Gateway
8,LH-A-042,2026-05-14T07:19:01Z,e0009,Powertrain,PT_1205,info,4,Idle speed stabilized,790.00,rpm,ECU
9,LH-A-042,2026-05-14T07:20:12Z,e0010,Hydraulic,HY_2003,info,4,Hydraulic oil temperature back to normal,78.60,C,ECU
10,LH-A-042,2026-05-14T07:21:40Z,e0011,Sensor,SN_3102,info,4,Temperature sensor plausible again,NaN,NaN,ECU
11,LH-A-042,2026-05-14T07:45:10Z,e0012,Powertrain,PT_1002,info,4,Ignition OFF,NaN,NaN,ECU

In [25]:
data.iloc[:,0]

0     LH-A-042
1     LH-A-042
2     LH-A-042
3     LH-A-042
4     LH-A-042
5     LH-A-042
6     LH-A-042
7     LH-A-042
8     LH-A-042
9     LH-A-042
10    LH-A-042
11    LH-A-042
Name: machine_id, dtype: object